apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  externalName: ec2-54-73-116-6.eu-west-1.compute.amazonaws.com
  selector:
    app: logstash
  type: ExternalName
status:
  loadBalancer: {}
