version: '2.1'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "ostock_dev", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      SPRING_PROFILE_ACTIVE: dev
      # This value should referenced as an OS environment variable, but for ease of usage it's defined here. It should also be random string of characters.
      ENCRYPT_KEY: INSYMETRIC
    networks:
      backend:
        aliases:
          - "configserver"

  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "licenseservice"


networks:
  backend:
    driver: bridge
