version: '2.1'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "ostock_dev", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      # This value is basically the master password for the project. Because of that it should be referenced as an OS
      # environment variable, but for ease of usage it's defined here. It should also be a random string of characters.
      ENCRYPT_KEY: INSYMETRIC
    networks:
      - backend

  eurekaserver:
    image: ostock/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    depends_on:
      configserver:
        condition: service_started
    networks:
      - backend

  gatewayserver:
    image: ostock/gatewayserver:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    depends_on:
      configserver:
        condition: service_started
    networks:
      - backend

  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_VERSION: 6.0.1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # This field is needed if keycloak server is in docker bridge network and the fronted app is trying to access it from the outside. The issuer in JWT body is set to this value.
      # It's value needs to match the internal hostname (keycloak), otherwise you will have mismatching issuers when trying to authenticate.
      KEYCLOAK_HOSTNAME: keycloak
      DB_VENDOR: h2
    volumes:
      - ./keycloak-config/keycloak-dev-config.json:/opt/jboss/keycloak/keycloak-dev-config.json
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/keycloak-dev-config.json"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8080:8080"
    networks:
      - backend

  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8180:8080"
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - licenseservice

  organizationservice:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      - backend


networks:
  backend:
    driver: bridge
